version: "3"

services:
  postgres:
    image: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=secret
    volumes:
      - studybuddy-data:/var/lib/postgresql/data/

  web-app:
    image: stuckenholz/studybuddyadmin
    ports:
      - 80:80
      - 443:443
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=secret
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - POSTGRESQL_HOST=postgres
      - POSTGRESQL_USER=postgres
      - POSTGRESQL_DATABASE=postgres
      - POSTGRESQL_PASSWORD=secret
    volumes:
      - type: bind
        source: ~/.aspnet/https/aspnetapp.pfx
        target: /https/aspnetapp.pfx

volumes:
  studybuddy-data:  