name: Build Xamarin.Android app

on: [push]

jobs:
  build-project:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set default Xamarin SDK versions
        run: |
          $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.10 --android=11.0

      - name: Setup .NET Core SDK 5.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Install dependencies
        run: nuget restore .

      - name: Build
        run:  msbuild ./StudyBuddy.App.Android/StudyBuddy.App.Android.csproj /t:PackageForAndroid /p:Configuration=Debug /p:OutputPath=bin/Debug

      - name: Upload Aritifacts
        uses: actions/upload-artifact@v2
        with:
          name: study-buddy-apk
          path: ./StudyBuddy.App.Android/bin/Debug/de.hshl.app.apk
    
  release-project:
    name: Release apk to Github Releases
    runs-on: ubuntu-20.04
    needs: build-project
    steps:
      - name: Download apk
        uses: actions/download-artifact@v2
        with: 
          -name: study-buddy-apk
      - name: Zip the the apk
        uses: thedoctor0/zip-release@master
        with: 
          filename: apk.zip
      - name: Create github release
        id: create-new-release
        uses: actions/create-release@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          tag_name: v${{ github.run_number }}
          release_name: Release V${{ github.run_number }}
      - name: Upload apk to github release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url}}
          asset_path: ./apk.zip
          asset_name: apk.zip
          asset_content_type: application/zip

      